### ISSUE TITLE
Publish Date format is different when written to lic file.

### ISSUE THREAD

**Issue by PrimeJoker** [skst/LicenseManager#4]
Setting the "Publish Date" to "14/05/2024" gets converted to "05/14/2024" in the *.lic file. On license validation, fails with the error "String '05/14/2024' was not recognized as a valid DateOnly."

**Comment by skst** [comment]
It was writing **PublishDate** with **InvariantCulture** but not parsing it with **InvariantCulture**.

Fixed in 4efbc9b2c6243f00df24c8168616d87bdc6c6e56 (v1.1.4).
